language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install -U codecov

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "ZkqKNkDvHBieyQ75+uLZI3dI5UgQl8vddQVqcBR+01m8j9HuREXtIgfI1y0psu9fJG5NDH2DVp3Wo9LZ/WY5IZcjY+eNWSz5e5v4yWCeoBVNN4q3fhmPv64ifrqZHVYXBxr7qpzT59vEB5GGISDEKHnRwYW6AIKW/4EXWFHgnh5JIIaD4sFF+vb0pgQsDOO2XkxLLR7NEDYQ4hwn2bFq9CLHlpPQvwS02duXk7HiWoFaFwBkDzNP7ckO1fEsNnymyA4FDowatDL9d6PBvK3LQE5q8WqtOOHF81xRMDsyANi1P89/pkYi+SvZuNd3m0pjyhF61r/I91Zc/lL3gfzVLSIisxwBtpYVvGzqul7euEC9PrLw9gsv8xhvPGxVkfrZ9vaizOE31f/AbqEZQinEEYQppyPN5JnLGa0FQCraBr+fXiSY+2+H7xeQy4VL1FAmXjBWVHAJy3Atn0l5VthD9+dj0y7W8ZITZ2Vw85jqCv5BbRc0M7LxT/3ESAJ7UirMqqvZ/xQ03d2w8IQyQ23eJGMptJdP1beTFMkGvvg7RolCeHHXb4yV0Ji538h3vD27ZOM0t3CbYkqeicb6BoU8juGEypNJUfdOxyG0Y/W1zK5QmdPkzP56umy4UX2rcr+Y8bSKiYMTnNSp8CsucTLfRCNH1Wg9hXIxHayUmRV5VRA="
  - secure: n4y7tnACPTcjBBDb6ZWc92Sk6KqLaAwrnASamPyj8QL2vV+rREWaJI6Bxb/7I/tzo0De1KpdjgrRU0RnxTpyvGlh/t+Da+0bLNHrPgO6+QvhRAjQPdUvuk2DiV0TF4ngbgvFRIsU0qzQ5zjlRCX4I5S/R4TtPWtzYgU4ZGj1K8S7FhawGmIcCG4Fd8BsyYAgT4Qt4m81BgZ/tyg7EAbga3rxvnn5KwnAOJV3ZJcuQT7cLgwEKSC428oO1kRm3gi9ePqoo7xAXfTfhWo37JSN5U6EbZ/4wZmOVCOqJ06gxQ/doTmStWjWhe6RCTMD7R7qEA+/oNakoBsqMoy1CRirJfcxOWAMfATOpEysw/RTnX0VlC915ZVBp94+fs0NPU3K6iL6tjsiKusHmwvyvkIGWs4Kb966A44RlIIUzEGUGUQA9rhCMa3fMncO1pL1qxvSfYi8C3kY8iEMkkfey1+KNFHKILLO7LCVyURxqAGlDYdmr96g8spsOq2f/6dWkXzL+Rtd7tjbOr4i84QmLizhdDCQjvzkXAfnqHbNyHG567hNdQWp25U0XQ9F+qAgh9OvqJ/1n0OJj+C40hz9I1870YyY+niIVYvlZSuhRS98pgxmONOLtEqAZr850B9BJtZdRpGXXkP7wdpOubaE1CENWkepreSnTWMSTYVTNB8G6gM=
script: 
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always

after_success:
  - codecov